# Generated by Django 4.2.1 on 2023-05-30 17:35

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_started', models.DateTimeField(default=datetime.datetime(2023, 5, 31, 0, 35, 12, 584046))),
                ('description', models.CharField(max_length=200)),
                ('session_length', models.DurationField()),
                ('focus_length', models.DurationField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DurationField(default=datetime.datetime(2023, 5, 31, 0, 35, 12, 584046))),
                ('image', models.ImageField(upload_to='analysis/')),
                ('confidence', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('status', models.BooleanField()),
                ('analysis_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fokus.analysis')),
            ],
        ),
    ]
