# Generated by Django 4.2.1 on 2023-06-10 19:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_started', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=200)),
                ('session_length', models.DurationField(null=True)),
                ('focus_length', models.DurationField(null=True)),
                ('ongoing', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='analysis/')),
                ('confidence', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('status', models.BooleanField(null=True)),
                ('analysis_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fokus.analysis')),
            ],
        ),
    ]
