# Generated by Django 4.2.1 on 2023-06-13 10:21

from django.db import migrations, models
import fokus.models


class Migration(migrations.Migration):

    dependencies = [
        ('fokus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisimage',
            name='image',
            field=models.ImageField(upload_to=fokus.models.path_and_rename),
        ),
    ]
