# Generated by Django 4.2.1 on 2023-06-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fokus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='ongoing',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='focus_length',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='session_length',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='time_started',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
