# Generated by Django 4.2.1 on 2023-06-02 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fokus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='ongoing',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='time_started',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 3, 2, 50, 51, 938294)),
        ),
        migrations.AlterField(
            model_name='image',
            name='timestamp',
            field=models.DurationField(default=datetime.datetime(2023, 6, 3, 2, 50, 51, 938294)),
        ),
    ]
