# Generated by Django 4.2.1 on 2023-06-10 18:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fokus', '0002_analysis_ongoing_alter_analysis_focus_length_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='analysis/')),
                ('confidence', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('status', models.BooleanField(null=True)),
                ('analysis_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fokus.analysis')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
