# Generated by Django 4.2.1 on 2023-06-02 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fokus', '0002_analysis_ongoing_alter_analysis_time_started_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='focus_length',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='session_length',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='time_started',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 3, 2, 58, 54, 775862)),
        ),
        migrations.AlterField(
            model_name='image',
            name='timestamp',
            field=models.DurationField(default=datetime.datetime(2023, 6, 3, 2, 58, 54, 775862)),
        ),
    ]
