# Generated by Django 4.2.1 on 2023-06-02 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fokus', '0003_alter_analysis_focus_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='time_started',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 3, 4, 7, 57, 198861)),
        ),
        migrations.AlterField(
            model_name='image',
            name='timestamp',
            field=models.DurationField(default=datetime.datetime(2023, 6, 3, 4, 7, 57, 198861)),
        ),
    ]
